### ISSUE TITLE
Missing file: iemocap_utils

### ISSUE THREAD

**Issue by ChiShao** [PiotrSobczak/speech-emotion-recognition#13]
“from speech_emotion_recognition.iemocap_utils.features import stFeatureExtraction”
This file is used in the audio_preprocessing.py，but I can't find it. 
Please tell me where can I find it? Thank you

**Comment by PiotrSobczak** [comment]
Hi @ChiShao! Im sorry, I removed these scripts some time ago by accident. I've just reuploaded them. :) Just pull from master
